#!/bin/sh -
#
# SCRIPT: shcal
# AUTHOR: Luciano D. Cecere
# DATE: 10/21/2017-01:56:43 AM
########################################################################
#
# shcal - display a calendar - POSIX version
# Copyright (C) 2017 Luciano D. Cecere <ldante86@aol.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

export PATH=/bin:/usr/bin
unalias -a
PROGRAM="${0##*/}"

month_names_long="January February March April May June July August September October November December"

_get_month()
{
	local c=0
	for i in $month_names_long
	do
		c=$(($c + 1))
		if [ $c -eq $1 ]; then
			echo "$i"
			return
		fi
	done
}
