#!/bin/bash -

_month_len()
{
        local m=$1 y=$2
        case $m in
                4|6|9|11)
                        echo 30
                        ;;
                1|3|5|7|8|10|12)
                        echo 31
                        ;;
                2)
                        _is_leap $y
                        if [ $LEAP ] ; then
                                echo 29
                        else
                                echo 28
                        fi
                        ;;
        esac
}

_is_leap()
{
        local y=$1
        unset LEAP
        if [ $((y % 4)) -eq 0 ] &&
           [ $((y % 100)) -ne 0 ] ||
           [ $((y % 400)) -eq 0 ]; then
                LEAP=1
        fi
}

_day_of_week()
{
        local m=$1 d=$2 y=$3

        local mcodes=(UNUSED 6 2 2 5 0 3 5 1 4 6 2 4)
        local w=$(( ((y / 4) - (y / 100)) + (y / 400) + d + y + ${mcodes[m]} ))

        _is_leap $y
        if [ $LEAP ] && [ $m -lt 3 ]; then
                ((w--))
        fi

        echo $((w % 7))
}

_gregorian_array_matrix()
{
        CALENDAR_DATA=()
        local m=$1 y=$2
        first_day_number_of_month=$(_day_of_week $m 1 $y)
        local len=$(_month_len $m $y)

        for ((i=1 ; i<=first_day_number_of_month; i++)); do
                if [ $first_day_number_of_month -eq 0 ]; then
                        break
                fi
                CALENDAR_DATA+=("  ")
        done

#        for ((i=1; i<=42; i++)); do
        for ((i=1; i<=$((60 - first_day_number_of_month)); i++)); do
                if [ $i -lt 10 ]; then
                        CALENDAR_DATA+=(" $i")
                elif [ $i -gt $len ]; then
                        CALENDAR_DATA+=("")
                else
                        CALENDAR_DATA+=($i)
                fi
        done
}

_print_gregorian_string()
{
        local m=$1 d=$2 y=$3

        _gregorian_array_matrix $m $y

        for ((i=0; i<${#CALENDAR_DATA[@]}-7; i++)); do
                echo -n "${CALENDAR_DATA[i]} "
        done

        echo
}

_print_gregorian_string_yearly()
{
        local m=$1 d=$2 y=$3
	local cycle=$4

	for n in {1..12}
	do
		echo "${cycle}_${n}=\"$(_print_gregorian_string $n $d $y)\""
	done
}

leap_cycle=( leap_cycle_{0..6} )
non_leap_cycle=( non_leap_cycle_{0..6} )

file=perpetual-strings.txt
>$file

t=0
for x in 1905 1906 1907 1913 1914 1915 1921
do
        if [ "${non_leap_cycle[t]}" = "$t" ]; then
                echo "${non_leap_cycle[t]}_${t}=\""
        fi
        _print_gregorian_string_yearly 1 1 $x ${non_leap_cycle[t]}
	echo
        ((++t))
done >> $file

t=0
for x in 1928 1940 1952 1964 1976 1988 2000
do
        if [ "${leap_cycle[t]}" = "$t" ]; then
                echo "${leap_cycle[t]}_${t}=\""
        fi
        _print_gregorian_string_yearly 1 1 $x ${leap_cycle[t]}
	echo
        ((++t))
done >> $file
