#!/bin/bash -

# PROGRAM: doc.sh
# AUTHOR: Luciano D. Cecere
# YEAR: 2016
# PURPOSE: Extract documentation from script files and create
# a manual. Special comment tags are:
#	"#%%"	is the header
#	"#% "	is the body

FILE="$1"

if [ -z "$FILE" ] || [ ! -e "$FILE" ]; then
	exit 1
fi

printf "\n%s\n\n" "# Function documentation manual for $FILE"

while read
do
	if [ "${REPLY:0:3}" = "#%%" ]; then
		#echo ----------------------------
		echo
		echo -n "Function: "
		fn=$(echo "${REPLY}" | sed 's/#%% //' | awk '{print $2}')
		echo "**${fn}**"
		echo
		a=$(echo "$REPLY" | sed 's/#%% //')
		echo -n "Parameters: **${fn}** "
		b=$(echo "$a" | cut -d" " -f 3-)
		echo "*${b}*"
	fi
	if [ "${REPLY:0:3}" = "#% " ]; then
		printf "\n\t"
		echo "$REPLY" | sed 's/#% //' | sed 's/purpose: //'
	fi
done < "$FILE"
