#!/bin/bash -

_gregorian_array_matrix()
{
        CALENDAR_DATA=()
        local m=$1 y=$2
        first_day_number_of_month=$(_day_of_week $m 1 $y)
        local len=$(_month_len $m $y)

        for ((i=1 ; i<=first_day_number_of_month; i++)); do
                if [ $first_day_number_of_month -eq 0 ]; then
                        break
                fi
                CALENDAR_DATA+=(0)
        done

        for ((i=1; i<=$((42 - first_day_number_of_month)); i++)); do
                if [ $i -lt 10 ]; then
                        CALENDAR_DATA+=($i)
                elif [ $i -gt $len ]; then
                        CALENDAR_DATA+=(0)
                else
                        CALENDAR_DATA+=($i)
                fi
        done
}

_print_gregorian_monthly_matrix()
{
        local m=$1 d=$2 y=$3

        _gregorian_array_matrix $m $y

	echo -n "[["

        for ((i=0; i<${#CALENDAR_DATA[@]}-7; i++)); do
                if [ $((i % 7)) -eq 0 ] && [ $i -ne 0 ]; then
			echo "]"
			echo -n " ["
		fi
		echo -n "(${CALENDAR_DATA[i]} $((i % 7))),"
        done

        echo "]]"
}

_print_gregorian_yearly_matrix()
{
        local m=$1 d=$2 y=$3

	echo  "[["

	for n in {1..12}
	do
		_print_gregorian_monthly_matrix $n $d $y
	done

	echo  "]]"
}
